---

- hosts: minion
  become: yes
  tasks:
    - name: take backup of config
      command: mv /etc/kubernetes/config /etc/kubernetes/config.backup
    - name: copy new config
      copy:
        src: config
        dest: /etc/kubernetes/
        mode: 644
    - name: take backup of kubelet
      command: mv /etc/kubernetes/kubelet /etc/kubernetes/kubelet.backup
    - name: copy new config
      copy:
        src: kubelet
        dest: /etc/kubernetes/
        mode: 644
    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
          - kube-proxy
          - kubelet
          - docker
    - name: stop firewalld
      command: systemctl stop firewalld
