---


- name: Check that the backup exists
  stat:
     path: "{{KUBE_APISERVER_FILE_BACKUP}}"
  register: stat_result

- name: Create the backup, if it doesnt exist already
  command: mv "{{KUBE_APISERVER_FILE}}" "{{KUBE_APISERVER_FILE_BACKUP}}"
  when: stat_result.stat.exists == False

- name: copy new config
  template:
     src: apiserver.j2
     dest: "{{KUBE_APISERVER}}"
     mode: 644
  notify:
     - name: restart kubernetesMaster
