---

- name: restart kubernetesMaster
  service:
     name: "{{ item }}"
     state: restarted
     enabled: yes
  with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
- name: restart kube-apiserver
  service:
     name: kube-apiserver
     state: restarted
     enabled: yes
  become: true
  become_user: root
