---

- name: restart kubernetesMaster
  service:
     name: "{{ item }}"
     state: restarted
     enabled: yes
  with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
