---

- name: restart kubernetesNode
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
       - kube-proxy
       - kubelet
       - docker
- name: stop firewalld
  command: systemctl stop firewalld
