---

- hosts: master
  become: yes
  tasks:
    - name: Check that the backup exists
      stat:
        path: /etc/kubernetes/config.backup
      register: stat_result
    - name: Create the backup, if it doesnt exist already
      command: mv /etc/kubernetes/config /etc/kubernetes/config.backup
      when: stat_result.stat.exists == False  
    - name: copy new config
      copy: 
        src: config
        dest: /etc/kubernetes/
        mode: 644
    - name: Check that the backup exists
      stat:
        path: /etc/etcd/etcd.conf.backup
      register: stat_result
    - name: Create the backup, if it doesnt exist already
      command: mv /etc/etcd/etcd.conf /etc/etcd/etcd.conf.backup
      when: stat_result.stat.exists == False
    - name: copy new config
      copy:
        src: etcd.conf
        dest: /etc/etcd/
        mode: 644
    - name: Check that the backup exists
      stat:
        path: /etc/kubernetes/apiserver.backup
      register: stat_result
    - name: Create the backup, if it doesnt exist already
      command: mv /etc/kubernetes/apiserver /etc/kubernetes/apiserver.backup
      when: stat_result.stat.exists == False
    - name: copy new config
      copy:
        src: apiserver
        dest: /etc/kubernetes/
        mode: 644
    - name: start services
      service: 
        name: "{{ item }}" 
        state: started
        enabled: yes
      with_items:
           - etcd
           - kube-apiserver
           - kube-controller-manager
           - kube-scheduler

