---

- name: Check that the backup exists
  stat:
     path: "{{KUBELET_BACKUP}}"
  register: stat_result
- name: Create the backup, if it doesnt exist already
  command: mv "{{KUBELET}}" "{{KUBELET_BACKUP}}"
  when: stat_result.stat.exists == False
- name: copy new config
  template:
     src: kubelet.j2
     dest: "{{KUBELET}}"
     mode: 644
  notify:
     - restart kubernetesNode
     - stop firewalld
