---

- name: Check that the backup exists
  stat:
     path: /etc/kubernetes/kubelet.backup
  register: stat_result
- name: Create the backup, if it doesnt exist already
  command: mv /etc/kubernetes/kubelet /etc/kubernetes/kubelet.backup
  when: stat_result.stat.exists == False
- name: copy new config
  copy:
     src: kubelet
     dest: /etc/kubernetes/
     mode: 644
  notify:
     - restart kubernetesNode
     - stop firewalld
