---

- name: install kubernetes
  yum :
     name: kubernetes
     enablerepo: "{{YUM_REPO_NAME}}"
     state: installed
- name: Check that the backup exists
  stat:
    path: "{{KUBE_CONF_BACKUP}}"
  register: stat_result
- name: Create the backup, if it doesnt exist already
  command: mv "{{KUBE_CONF}}" "{{KUBE_CONF_BACKUP}}"
  when: stat_result.stat.exists == False
- name: copy new config
  template:
     src: config.j2
     dest: "{{KUBE_CONF}}"
     mode: 644
