---

- name: install etcd
  yum :
      name: etcd
      enablerepo: "{{YUM_REPO_NAME}}"
      state: installed
- name: Check that the backup exists
  stat:
      path: "{{ETCD_CONF_BACKUP}}"
  register: stat_result
- name: Create the backup, if it doesnt exist already
  command: mv "{{ETCD_CONF}}" "{{ETCD_CONF_BACKUP}}"
  when: stat_result.stat.exists == False
- name: copy new config
  template:
       src: etcd.conf.j2
       dest: "{{ETCD_CONF}}"
       mode: 644
  notify:
     - restart etcd
